### ISSUE TITLE
[Feature] Support for C#

### ISSUE THREAD

**Issue by DSaunders** [medyo/hackertab.dev#10]
Would you take a PR for C# support?

**Comment by Med-NAIMI** [comment]
![HackerTab](https://user-images.githubusercontent.com/56475732/109022926-98895b80-76bc-11eb-9251-63cadc3da40e.PNG)

there is no c# in the dropdown list that appears after clicking the select icon!

**Comment by medyo** [comment]
It's not yet merged, I'll let you know when it's live

**Comment by medyo** [comment]
Merged and deployed to Chrome (pending) & Firefox (accepted)
