### ISSUE TITLE
 Dev.to and medium pages are shown the same problem.

### ISSUE THREAD

**Issue by ardakazanci** [medyo/hackertab.dev#102]
Dev.to and medium pages are shown the same. Another problem I noticed is that the current articles are not coming according to the specific programming languages. (updated problem.)

**Comment by medyo** [comment]
you're right, there is a bug in the medium fetch api, We're working on it.
@ardakazanci  Regarding your second question, is it related to Devto or Medium ?

**Comment by ardakazanci-mobven** [comment]
probably dev.to and medium articles are not showing up-to-date content. For example; When I say show contents for Kotlin programming language. Showing old content.
