### ISSUE TITLE
Duplicated data rows in Medium list

### ISSUE THREAD

**Issue by aminekarimii** [medyo/hackertab.dev#105]
Followed languages: **Kotlin, Android**  
Selected sources: **Product hunt, Reddit, Medium, Hackernews**

![image](https://user-images.githubusercontent.com/20410115/206725886-87c8352f-f945-421d-a420-570998bd9fa0.png)

**Comment by medyo** [comment]
Thanks @aminekarimii for reporting the bug, actually when two tags or more have the same article (eg: android and kotlin), the redundant item get displayed twice.
We're working on it.
