### ISSUE TITLE
Add more subreddits within the Reddit tab section

### ISSUE THREAD

**Issue by DLRAM** [medyo/hackertab.dev#108]
like we can switch between subreddits ,there are more useful subreddits available like

/r/learnprogramming: A subreddit for those looking to learn how to program.
"its already there "/r/programming: A subreddit for those interested in programming and computer science.
/r/coding: A subreddit for coding and programming enthusiasts.
/r/webdev: A subreddit for those interested in web development.
/r/compsci: A subreddit for computer science students and professionals.

**Comment by Chouikane** [comment]
the mentioned subreddits were added, and found under the `Trending` option.
