### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by chixing** [medyo/hackertab.dev#109]
Would be nice to have either of the following:
- horizontal scrolling with trackpad/mouse without having to click the left/right buttons
- an option to make the boxes are stack vertically instead

**Comment by medyo** [comment]
The first request is a duplicate of #86
I'll try to find a way to handle the horizontal scroll.

Can you create another new issue for your second request with more details?

**Comment by chixing** [comment]
I'm ok with just the first option
