### ISSUE TITLE
support for less than 4 sources

### ISSUE THREAD

**Issue by byt3h3ad** [medyo/hackertab.dev#115]
currently opening less than 4 sources leaves a blank space for the fourth space, which looks ugly. making it dynamic such that it adjusts the space will look much cleaner.
[(what im talking about)](https://i.imgur.com/7rnxGwX.png)

**Comment by medyo** [comment]
It's done on purpose to keep each card in a good shape. 
There are some cases where flexible width won't work like having 1 card. it'll occupy the full screen width. 
What do you think?

**Comment by lennarto** [comment]
I would make the number of columns adjustable :) 

https://github.com/medyo/hackertab.dev/issues/143
