### ISSUE TITLE
[Feature] Chance dev.to blog list section to dev.to + hashnode 

### ISSUE THREAD

**Issue by jai-dewani** [medyo/hackertab.dev#13]
**Pros:** Hashnode according to me is another blogging platform that seems to be up and coming and can be added to the list to bring some diversity to the list but 

**Cons:** This can be discussed upon because if decide to hashnode then there are 20 similar platforms with awesome blogs that can also be added

**Comment by medyo** [comment]
We actually decided to add hashnode but in a standalone card.
We may merge the content from Devto and Hashnode on the upcoming iterations
