### ISSUE TITLE
Adjustable number of columns

### ISSUE THREAD

**Issue by lennarto** [medyo/hackertab.dev#143]
Hi, 

I have a wide screen and therefore 5-6 columns would fit perfectly.
I think it would be awesome to have the column number adjustable in the settings.

Thanks!

**Comment by medyo** [comment]
That's interesting, this should be available in the next version
thanks for the suggestion @lennarto

**Comment by lennarto** [comment]
Thanks!! Awesome response time 🚀🔥🎉

**Comment by medyo** [comment]
@lennarto what's your screen resolution?

**Comment by lennarto-berylls** [comment]
Current Setup:
Macbook Air M2: 2560 x 1664
External: 2560 x 1440

Office Setup: 
We have many different wide external monitors (shared space), I cant look uo the resolution right now :)

**Comment by medyo** [comment]
I'll close this as the feature has been implemented and deployed !
