### ISSUE TITLE
Add a new programming language 'solidity' 

### ISSUE THREAD

**Issue by ronykris** [medyo/hackertab.dev#153]
Basically to source articles and information associated to solidity.

**Comment by lazyfuhrer** [comment]
Hey I'd like to work on this. Assign me @ronykris

**Comment by ronykris** [comment]
@medyo can this be assigned to @lazyfuhrer ?

**Comment by RishabhJain-11** [comment]
Hey, just want to ask about whether this issues assigned to someone or not. Because I'm interested in this issue. Please @ronykris let me know.

**Comment by ronykris** [comment]
I do not think it's assigned yet. The maintainer hasn't responded.

Had I been you I would have fixed/implemented it and created a PR.
Chances of duplication could be there, but atleast you will get your stuff
done.

**Comment by medyo** [comment]
@ronykris @RishabhJain-11 This task requires both frontend/backend changes, unfortunately, the backend isn't open for contributions.
Thank you again guys!

@Chouikane can you handle this?

**Comment by medyo** [comment]
@ronykris Solidity language added.
it should be available within a few minutes.
If you don't see the changes, clear your cache.
