### ISSUE TITLE
add phind.com as search engine to hacktab

### ISSUE THREAD

**Issue by MustCodeAl** [medyo/hackertab.dev#158]
phind.com is a nice new ai search engine for programmers, it would make more sense to use on hackertab, since I tend to google directly from my address bar.

**Comment by medyo** [comment]
Seems interesting, can you make a pull request of the request search engine?
https://github.com/medyo/hackertab.dev/blob/a5857c8646d93af3c43abd43f6d1d55d86894dcc/src/config/index.tsx#L47C5-L47C5

**Comment by MustCodeAl** [comment]
done
