### ISSUE TITLE
Fix post's date calculation

### ISSUE THREAD

**Issue by nafiul-adnan** [medyo/hackertab.dev#159]
Some cards are showing 53 years ago on the duration/age of the post. See attached image- 

![date-issue](https://github.com/medyo/hackertab.dev/assets/143912167/d9caae8c-a130-4069-8afd-7c6ad4b9e660)

**Comment by medyo** [comment]
@nafiul-adnan which source is that?

**Comment by idebenone** [comment]
Hey @medyo !

I noticed this bug on Hashnode card.

**Comment by medyo** [comment]
The bug has been fixed!

**Comment by nafiul-adnan** [comment]
Thanks a lot.

Sorry I couldn’t have any follow-up!
