### ISSUE TITLE
Option to share articles/posts/news link on social media 

### ISSUE THREAD

**Issue by idebenone** [medyo/hackertab.dev#161]
Hey @medyo !
We can add an button next to bookmark to share link on social media. 

![image](https://github.com/medyo/hackertab.dev/assets/114807970/2d965a35-8ffd-4101-be86-f98fa774ed22)
![image](https://github.com/medyo/hackertab.dev/assets/114807970/5901cf97-d760-42c4-8521-5481544763b7)

I would link to work on this .

**Comment by medyo** [comment]
Awesome,
Yes, feel free to work on it

**Comment by idebenone** [comment]
Hey @medyo !
It's done 😁.

**Comment by medyo** [comment]
Perfect, I'll review your pull request
