### ISSUE TITLE
Disable transitions on theme toggle

### ISSUE THREAD

**Issue by yefreescoding** [medyo/hackertab.dev#163]
I've noticed that when switching to light mode and vice versa, the page transition causes the colors of the components to change at different times. This might be caused by varying transition values for each component. There's a simple and easy way to solve this problem, and this article explains it quite effectively.
Link:
https://paco.me/writing/disable-theme-transitions

**Comment by medyo** [comment]
Looks interesting, could you spare a moment to submit a pull request?
