### ISSUE TITLE
Feature Request: Add support for Reddit Login / Custom Subreddit support.

### ISSUE THREAD

**Issue by Welding-Torch** [medyo/hackertab.dev#165]
Hi, I really love hackertab.dev and I've made it my homepage, but there's one thing I'd really like it to support: Showing me news from the **subreddits that I subscribe to**, instead of just the default ones. Perhaps an option to 'Sign In With Reddit' could be added to the extension, and then it'll display posts from the subs I read. Or if you want to avoid signing in, then simply provide a textbox where I can enter the names or links of my favourite subreddits.

**Comment by medyo** [comment]
Unfortunately, we don't have that feature and it's not in our plans for the future.
However, you can try a workaround by creating a custom RSS feed (hosted on Netlify or Vercel) from your own content and then use that with Hackertab. We do support custom feeds, so that should do the trick!

**Comment by Welding-Torch** [comment]
Hey, even though you don't have that feature, maybe you could add it to your plans for the future? I'm sure lots of people will appreciate it if you do.

Either way, peace ❤️

**Comment by medyo** [comment]
If many users show interest, I may reconsider adding it.
 thanks again
