### ISSUE TITLE
Feature Proposal: Product Hunt topics and posts

### ISSUE THREAD

**Issue by Ivan-Marquez** [medyo/hackertab.dev#17]
I use [Product Hunt](https://www.producthunt.com/) as my home page, it'd be great if I could see their posts from Hackertab! And they have a [GraphQL API](https://api.producthunt.com/v2/docs) for this. Thanks!

**Comment by medyo** [comment]
Thanks, @Ivan-Marquez, Producthunt listing has been added, it should be available in the coming version
