### ISSUE TITLE
[BUG] Angle brackets aren't displayed correctly

### ISSUE THREAD

**Issue by EDM115** [medyo/hackertab.dev#174]
They are instead displayed as their HTML symbol (`&lt;` | `&rt;`) :  
![image](https://github.com/medyo/hackertab.dev/assets/82015596/edffdc2d-8005-4cce-9d2b-bd19effdc85d)
![image](https://github.com/medyo/hackertab.dev/assets/82015596/40aa6f58-0274-476f-a89b-7d4e68831b02)

**Comment by medyo** [comment]
Nice catch, this seems to be an encoding issue while crawling the reddit content.
I'll take a look

**Comment by EDM115** [comment]
also happens with `&` (`&amp;`) :  

![image](https://github.com/medyo/hackertab.dev/assets/82015596/793fce8f-c4cb-409e-9f08-42a9fc56b814)
![image](https://github.com/medyo/hackertab.dev/assets/82015596/3e4dfbb5-28f6-4e40-a182-cfe9b71c9efc)

**Comment by medyo** [comment]
Fixed, it should be available within a few minutes. 
If you don't see the changes, clear your cache.

<img width="424" alt="image" src="https://github.com/medyo/hackertab.dev/assets/2389584/3f71fc3e-8f36-47dd-87a5-8d82c1038f40">

**Comment by EDM115** [comment]
yep, works :)
