### ISSUE TITLE
The purpose of choosing languages you're interested in

### ISSUE THREAD

**Issue by danboyce92** [medyo/hackertab.dev#175]
Hey there,
What does choosing specific languages you're interested in actually do? I opened this up in my local environment hoping to tackle issue #67 
But now that I'm clicking specific languages and unclicking them I don't see any difference in the news feed. What is it exactly that they do? I was hoping to work on #67 and sort the news feed dynamically by chosen languages but now I'm thinking simpler and even just highlighting the items that contain a language that has been favorited.
Is this something that could be useful?
Thanks,
Dan

**Comment by medyo** [comment]
When you add your favorite technologies, each card becomes unique. For example, you can see Typescript news from Devto and Python stuff on Reddit. This makes it super flexible. But I get it, you're thinking about combining all articles into one feed and letting users pick and choose by tech or source. right?

<img width="424" alt="image" src="https://github.com/medyo/hackertab.dev/assets/2389584/d66c6ef4-c311-494f-aeb3-57693a3a8914">

**Comment by danboyce92** [comment]
Ah I didn't see trending was clickable. 
This makes it way better!
Putting it into one feed and being able to filter by language or source would be cool but honestly the way you have it is top notch. Great extension!
