### ISSUE TITLE
[BUG] Reddit seems blocked in time

### ISSUE THREAD

**Issue by EDM115** [medyo/hackertab.dev#177]
For some reason, the reddit card doesn't show up to date info  
The trending posts are from 3 days ago, the upvote counters aren't up to date, ...  
is that again some reddit f*cking api thing ?

clearing cache on reddit.com & removing/readding the reddit card doesn't change a thing

**Comment by medyo** [comment]
@EDM115 could you check now?

**Comment by EDM115** [comment]
fixed 👍

**Comment by EDM115** [comment]
sad to say it but the issue is back

**Comment by medyo** [comment]
Thanks @EDM115 for reporting that,
Unfortunately the server IP has been blocked by reddit for some reason, many people have the same issue, I've submitted a request to get an access. I'll keep you update

```
whoa there, pardner!
reddit's awesome and all, but you may have a bit of a problem.

Make sure your User-Agent is not empty, is something unique and descriptive and try again. if you're supplying an alternate User-Agent string, try changing back to default as that can sometimes result in a block.

If you're attemping to access Reddit via a hosting provider or private VPN, please either login at [reddit.com/login/](https://www.reddit.com/login/) or register/sign in with your developer credentials [here](https://www.reddit.com/wiki/api/).

You can read Reddit's Terms of Service [here](https://www.reddit.com/wiki/api/).

if you think that we've incorrectly blocked you or you would like to discuss easier ways to get the data you want, please contact us at [this email address](mailto:ratelimit@reddit.com?Subject=Blocked%20XXX.XXX.XXX.XXX).

when contacting us, please include your ip address which is: XXX.XXX.XXX.XXX and reddit account
```

**Comment by EDM115** [comment]
have to say it : it seems back to normal

**Comment by medyo** [comment]
Yep, I switched from making public requests to authorized ones using the credentials from the new Reddit developer app I made. 
I deployed the new changes yesterday and waited to check if all the Reddit API calls were working throughout the day without any limitations.

So we're good now! Thanks again @EDM115
