### ISSUE TITLE
Custom search engine

### ISSUE THREAD

**Issue by nargacu83** [medyo/hackertab.dev#178]
Hi, it would be great if we could add custom search engines with the ability to specify the URL, just like Firefox.
An example would be _**SearXNG**_ which can be selfhosted on a local network.

**Comment by medyo** [comment]
@nargacu83 Would you like to work on it? The code is already there, might just need some minor adjustments.

**Comment by nargacu83** [comment]
Sure, i can try to do it.

**Comment by MohammedAslam106** [comment]
> Sure, i can try to do it.

Hey, are you working on it.

**Comment by nargacu83** [comment]
@MohammedAslam106 No, i haven't had much time to work on this. If you want to do it instead, go ahead!
