### ISSUE TITLE
[BUG] Comments in AI source always leads to a random HackerNews comment

### ISSUE THREAD

**Issue by EDM115** [medyo/hackertab.dev#186]
https://github.com/medyo/hackertab.dev/assets/82015596/6d323e02-d6af-437e-af41-4629b9b7dc39

whatever is the source. it always is a random HackerNews comment

**Comment by medyo** [comment]
I duplicated the Hackernews card and forgot to remove the comments url.
It's fixed right now, it will be available in the coming version.
Thanks @EDM115 for reporting the issue
