### ISSUE TITLE
hackernews: option to open comments

### ISSUE THREAD

**Issue by NickLarsenNZ** [medyo/hackertab.dev#192]
I tend to read hackernews comments first, before deciding if I want to dive into the linked article.

It would be nice to have some kind of configuration to enable/disable that - or perhaps an extra button next to each item in the list.

**Comment by NickLarsenNZ** [comment]
@medyo that's on the Hacker news site. But how do I go straight to comments from Hackertab?

![image](https://github.com/medyo/hackertab.dev/assets/10092581/17e4ba27-772d-4ee4-b80b-9e373e4561c9)

**Comment by medyo** [comment]
@NickLarsenNZ you're currently using compact mode, which hides all distracting elements. To access the comments links again, you'll need to disable this mode.
<img width="409" alt="image" src="https://github.com/medyo/hackertab.dev/assets/2389584/e01d9440-e909-423f-b7e8-4036effb86ee">

**Comment by NickLarsenNZ** [comment]
Thanks @medyo, I didn't even think to try switching that back :)
