### ISSUE TITLE
Brave search engine

### ISSUE THREAD

**Issue by mirzap** [medyo/hackertab.dev#194]
I wonder why the Brave engine is not on the list?

**Comment by medyo** [comment]
Would you like to work on this? it's similar to: https://github.com/medyo/hackertab.dev/pull/190

**Comment by mirzap** [comment]
Sure! Thanks for the reference.

**Comment by mirzap** [comment]
Wonder why revert?

**Comment by medyo** [comment]
@mirzap I did a mistake by merging your work into the master branch, can you create another PR to the develop branch

thanks
