### ISSUE TITLE
hashnode articles not up-to-date

### ISSUE THREAD

**Issue by siska77** [medyo/hackertab.dev#205]
I've got a column for hashnode for the category/tag **php** but the last article is from 3 months ago, while there are many more new articles on hashnode itself
https://hashnode.com/n/php

**Comment by siska77** [comment]
Forgot to say I'm using **Firefox** on **Ubuntu 20.04.6**
![htss](https://github.com/user-attachments/assets/0bac056f-f434-48e3-b886-d56abd915587)

**Comment by siska77** [comment]
As of today the column shows new articles.  
I don't know if somebody did something or it's just a coincidence, if it's the first: **Thanks!**

**Comment by medyo** [comment]
Hi @siska77, Yes, I fixed the issue but I waited until the extension and server cache were cleared.
