### ISSUE TITLE
PHP language support

### ISSUE THREAD

**Issue by courane01** [medyo/hackertab.dev#25]
I would like to turn on HTML, CSS, and PHP programming languages. 

I would also like to enable WordPress developer job postings. 

With those, I would suggest this extension to the jr dev bootcamp participants.

**Comment by medyo** [comment]
The `PHP` language is already there.
`HTML ` & `CSS` are not technically programming languages, they are mainly used to markup the page structure, styles...
With that in mind, the majority of `Javascript` jobs require implicitly knowing HTML & CSS, so no need to mention them.

Regarding the WordPress request, I'm not sure it applies to our roadmap, but If many people show interest, we'll definitely reconsider reviewing this decision.
