### ISSUE TITLE
Change the style of scroll bars in firefox

### ISSUE THREAD

**Issue by aayushmau5** [medyo/hackertab.dev#3]
First of all, this is a great extension. But in firefox(especially in linux), the scroll bar looks ugly.
![scrollbar](https://user-images.githubusercontent.com/54525741/108617583-ab422d00-743d-11eb-983c-a963dc949073.png)
**Suggestion**:  Change the style of the scrollbar to match the theme(especially in black theme).

**Comment by medyo** [comment]
Hi @aayushmau5,

I can't reproduce the bug as I'm using Mac,
Could you check the fix I did at: `fix/firefox-scrollbar` and let me know if it's working thanks

**Comment by aayushmau5** [comment]
![fix](https://user-images.githubusercontent.com/54525741/108629022-ff700000-7483-11eb-8f94-a67dec5ca443.png)

Looks like it's fixed. Thanks a lot @medyo for this.

**Comment by medyo** [comment]
Alright, the fix should be deployed tomorrow.

**Comment by medyo** [comment]
The commit has been deployed!
