### ISSUE TITLE
news source reccomendation: rekt news

### ISSUE THREAD

**Issue by Kampe** [medyo/hackertab.dev#46]
https://feed.rekt.news/

**Comment by medyo** [comment]
I'm not sure Rekt.news is a suitable source for developers, as it's 100% related to the financial world.

**Comment by Kampe** [comment]
I'd disagree, it's similar to hackernews, except for solely relating to blockchain technology. There's a lot of software engineering topics here.

**Comment by Lissy93** [comment]
Maybe an RSS tab feature would be a good feature? As almost all blogs, news sites and aggregators support RSS, and it would allow users to add their own sources. I'd be happy to submit a PR for that if you're up for it?

**Comment by medyo** [comment]
@Lissy93 hum... the feature sounds interesting.
I'll think about it and let you know if it fits in our roadmap.

**Comment by medyo** [comment]
Thanks for the suggestion @Lissy93. We think it's a great idea and we'd love to see it added to the project. If you're interested in submitting a PR for it, I'd be happy to review it and get it merged. 
I've opened the feature discussion here with some specs, https://github.com/medyo/hackertab.dev/discussions/111, Let me know if you have any questions or need any help.
