### ISSUE TITLE
Feature Proposal: Popular Articles

### ISSUE THREAD

**Issue by aymaneMx** [medyo/hackertab.dev#5]
A card for the popular articles (maybe just medium articles for now) related to a specific tag.

**Comment by medyo** [comment]
Actually, we show the top articles from `DevTo`, How do you rate their content?
Do you think we should replace it with Medium or make another tab for medium articles?

**Comment by aymaneMx** [comment]
I like `DevTo` content! .. it'll be great to have a card called `Articles` -for example- that fetch articles from diff sources, and the user has the right to filter depending on his preferences. 
what do you think?

**Comment by medyo** [comment]
I'm not sure Medium has a public API that provides top articles of the day
