### ISSUE TITLE
Consider allow multiple Programming Language selection

### ISSUE THREAD

**Issue by Dentrax** [medyo/hackertab.dev#56]
Currently, we can only choose one programming language at a time. It would be great if we have ability to select more than one since most of the people interested in several programming languages. Wdyt?

![Screen Shot 2021-09-13 at 16 36 00](https://user-images.githubusercontent.com/16493751/133093302-7cdf6b14-04d6-4413-a2c1-8da45a57f49a.png)

**Comment by medyo** [comment]
Hi @Dentrax ,

Actually, you can select as many languages as you want, there is no limit
Here is an example
![image](https://user-images.githubusercontent.com/2389584/133109693-c4724b7c-710f-434b-9982-eda1e326c81a.png)
