### ISSUE TITLE
More than 4 cards?

### ISSUE THREAD

**Issue by akumanara** [medyo/hackertab.dev#64]
As the title suggests

**Comment by medyo** [comment]
Having more than 4 cards will ruin the user experience as it won't be enough space to display the data correctly.
However we can design new types of layout that are not necessarily horizontal but as a grid where you can have a bit of data of your favorite sources. something like ([image](https://www.tutorialspoint.com/angular_material7/images/angular_material7_grid_list.jpg))
What do you think?

**Comment by akumanara** [comment]
Good idea. Is it a requirment to have all the cards in the viewport? Can we just have scrolling with more cards on bottom?

**Comment by medyo** [comment]
Hi @akumanara,

Check this first version of the horizontal scroll and let me know what you think
https://imgur.com/MXwjrVB

**Comment by akumanara** [comment]
Looks great! Do you want any help with the implementation?

**Comment by medyo** [comment]
It's actually already implemented (should be released asap), but thanks for your help.
If you'd like to contribute in the upcoming features, you're more than welcome
