### ISSUE TITLE
Consider make "X repos of Y" configurable

### ISSUE THREAD

**Issue by Dentrax** [medyo/hackertab.dev#68]
We currently could not configure the default value of "X repos of Y" section.

![Screen Shot 2021-11-02 at 10 55 58](https://user-images.githubusercontent.com/16493751/139807336-a886b10f-3763-4cc6-bbe2-2f4d37b5929e.png)

What would it look like if we add a brand-new config section (2 dropdown list) just under the "Favorite search engine"?

![Screen Shot 2021-11-02 at 10 56 50](https://user-images.githubusercontent.com/16493751/139807470-dea06777-2a5c-4a96-9419-57003da976a5.png)

**Comment by medyo** [comment]
What about saving the previous user choice for a better flexibility.
For example, if your last visited repos are `Devos repos of the month`, you'll get the same for your next visit until you change it

**Comment by Dentrax** [comment]
Oh, sure! I think that much make better way! Thanks for the idea.
