### ISSUE TITLE
Consider add "All interesting" choice in the "repos"

### ISSUE THREAD

**Issue by Dentrax** [medyo/hackertab.dev#69]
I think it would be great to see only _interested tags_ in a single place for GitHub just like how DevTo and Reddit it is. 

![Screen Shot 2021-11-02 at 11 13 48](https://user-images.githubusercontent.com/16493751/139809623-18f74695-d7c7-490c-8444-b6fa1704d979.png)

What can we do here:
* api call to get latest tags for `go`: https://github.com/trending/go?since=daily
* api call to get latest tags for `rust`: https://github.com/trending/rust?since=daily
* ...
* combine the results and order by _x stars today_ field

**Comment by medyo** [comment]
I think that's doable,
@Chouikane can you handle this?

**Comment by Chouikane** [comment]
Done. Thanks @Dentrax for the suggestion.
