### ISSUE TITLE
Bug: GitHub does not list projects if non-existed tag given

### ISSUE THREAD

**Issue by Dentrax** [medyo/hackertab.dev#74]
A few days ago, @Chouikane did such a cool job about adding "My Languages" option to GitHub and that is awesome! Thanks! 🎉 

There is a small issue about the listing projects though, If I set a non-existed tag, GitHub stops working and does not work as expected. i.e., for `Devops` tag, maybe another tags. We should probably find a way out to exclude non-existed tags here.

https://api.hackertab.dev/data/github/devops/daily.json <-- `404`

v1.11.0

![Screen Shot 2021-11-10 at 22 34 40](https://user-images.githubusercontent.com/16493751/141181122-2595fae6-21a5-4426-8313-f6ab42795bd2.png)

**Comment by medyo** [comment]
Fixed and pushed
The update should be available in the coming hours
