### ISSUE TITLE
New tab stops responding & slowing down the Firefox

### ISSUE THREAD

**Issue by Dentrax** [medyo/hackertab.dev#78]
Actually, this problem did not exist a few weeks ago. Somehow, every _X_ new tab open, the following case occurs:

![Screen Shot 2021-11-29 at 09 22 02](https://user-images.githubusercontent.com/16493751/143824395-eb0793ba-5d45-43ec-af8b-120f81ea2684.png)

Disabling the expansion fixes the issue.

```
Hackertab.dev 1.11.1
Firefox 94.0.2
macOS 11
```

My configuration:

![Screen Shot 2021-11-29 at 10 47 23](https://user-images.githubusercontent.com/16493751/143827915-89a1b0a9-6430-438b-98c9-6b6ea0be8d8d.png)

Any ideas?

**Comment by medyo** [comment]
@Dentrax That's really strange, is it always the case?
if so, can you do a performance check and share with me the report (you can send it to hello@hackertab.dev).
Thanks

**Comment by Dentrax** [comment]
@medyo Hey! Just noticed that this bug happens if I set to `My Languages`. I used with the `All Trending` setting a few days and bug never occurred. Probably some logic causes an infinite loop or smth.


![Screen Shot 2022-01-03 at 09 07 31](https://user-images.githubusercontent.com/16493751/147903322-d2410e4b-778d-4f33-95c4-9c05a5d409aa.png)

**Comment by medyo** [comment]
Alright @Dentrax, thanks for this clue
@Chouikane can you take a look into this?

**Comment by medyo** [comment]
Hi @Dentrax, can you list the tags you follow on hackertab?

**Comment by Dentrax** [comment]
> Hi @Dentrax, can you list the tags you follow on hackertab?

![Screen Shot 2022-01-10 at 21 57 41](https://user-images.githubusercontent.com/16493751/148823198-29d4ae3e-06d5-4b79-91c9-e215c1b9d840.png)
