### ISSUE TITLE
DEV tab only works with a single language

### ISSUE THREAD

**Issue by andypiper** [medyo/hackertab.dev#79]
If I remove the language options from the top of the new tab (hackertab) page, the DEV tab is empty. If I add more than one language to my settings, only the first one is reflected in the data retrieved from DEV. This is reflected in the code for the DEV service only accepting a single language tag. There's no indication why no data is displayed if I remove all languages from my interests, and there's no way to choose what I want to see from DEV (unlike the GitHub column).

**Comment by medyo** [comment]
Actually the DEV column shows a merged content of all your added languages, it doesn't have a proper filter option like Github.
I think we could add this in the coming version
