### ISSUE TITLE
Ads errors

### ISSUE THREAD

**Issue by andypiper** [medyo/hackertab.dev#81]
JS console shows

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://*.carbonads.com https://*.buysellads.net https://*.buysellads.com https://*.servedby-buysellads.com https://*.carbonads.net". Either the 'unsafe-inline' keyword, a hash ('sha256-9wgUeE7o26PX9BlGznRgR+gJarj/ugHxm3UOzKP13EE='), or a nonce ('nonce-...') is required to enable inline execution.`

I'm worried about this extension calling domains I did not expect, so I'm removing it locally.

**Comment by medyo** [comment]
Those lines are safe and used to whitelist the CarbonAds resources in order to display the ads correctly.
We use CarbonAds as a revenue model to cover the costs of services eg (Server, Domain name, apis...)
