### ISSUE TITLE
Scroll click (middle mouse click) isn't working correctly both on the website & extension

### ISSUE THREAD

**Issue by Droyk** [medyo/hackertab.dev#86]
I make heavy use of scroll click so if it doesn't work correctly anywhere that immediately becomes a huge downer! please fix it!

**Comment by medyo** [comment]
Hi @Droyk,
What behaviour are expecting when clicking on the middle the scroll button?

**Comment by Droyk** [comment]
apologies forgot to add what was wrong with it! Hmm, this is strange seems like the issue got fixed. the issue was scroll click was interacting with clickable links & other interactive elements in the scroll process. which was immediately stopping the scrolling process. and I had to again click on the scroll click to enable the scroll again though this wasn't happening while using the scroll wheel! but now I can't reproduce it seems like it was from my end. 

but since I've already made the issue I have a request wouldn't it be better to scroll the inactive columns with scroll click just like users do with the scroll wheel
currently, scrolling while the scroll click is active doesn't work for the inactive columns only the active one can scroll up & down https://gfycat.com/ifr/madniceduckbillplatypus?controls=0&hd=1
& scroll click also doesn't work if the cursor isn't inside the columns it won't even activate! I would like to see it active so whenever I hit scroll click no matter where the cursor is on the page except clickable links it activates the scrolling function and then starts scrolling whenever the cursor gets over a column.

**Comment by medyo** [comment]
I've found a way to do it, it should be available in the coming version.
Thank you guys
