### ISSUE TITLE
Stackoverflow remote jobs source is not working anymore [due to stackoverflow jobs section discontinuity]

### ISSUE THREAD

**Issue by aminekarimii** [medyo/hackertab.dev#87]
The StackOverflow jobs source is now useless, the links in this section are not working anymore.
You should remove it.
source: https://meta.stackoverflow.com/q/415293

**Comment by medyo** [comment]
Thanks @aminekarimii for reporting it,
I'll hide the card until we find another alternative offering a public api

**Comment by medyo** [comment]
Fixed
