### ISSUE TITLE
[ Add Search Engine ] Presearch

### ISSUE THREAD

**Issue by devarshishimpi** [medyo/hackertab.dev#93]
Could Hackertab have a decentralized search engine added like [presearch.com](https://presearch.com/signup?rid=4339531)?

**Comment by devarshishimpi** [comment]
@medyo Any updates on this?

**Comment by medyo** [comment]
I'm not really sure it's a famous search engine among developers.
I'd appreciate hearing more comments on the matter. If many users show interest, I may reconsider adding it .
