### ISSUE TITLE
Some sources stopped working (does not update)

### ISSUE THREAD

**Issue by Dentrax** [medyo/hackertab.dev#99]
HackerNews seems still working and other ones stopped working for 2 weeks. Any ideas on this? 🤔 

Reinstalled the extension, also have cleared the all cache and storage from the browser, but the issue still persists.

```
Version
1.14.3
```

![Screenshot 2022-11-18 at 10 15 13](https://user-images.githubusercontent.com/16493751/202643371-de4678a9-2a26-46e5-8489-9396acbff486.png)

**Comment by Chouikane** [comment]
Fixed.

**Comment by Dentrax** [comment]
Thanks for prompt action @Chouikane! But it seems Reddit is broken:

![Screenshot 2022-11-19 at 17 44 07](https://user-images.githubusercontent.com/16493751/202856532-767d11eb-5db9-4d65-b42f-6c4924da5c18.png)
